"""Constants for text checking."""

MAX_TEXT_LENGTH = 10000

GRAMMAR_RULE_PREFIXES = (
    "SVA",
    "AGREEMENT",
    "CONFUSION",
    "CONFUSED_WORDS",
    "TENSE",
    "VERB",
    "PREPOSITION",
    "ARTICLE",
    "PRONOUN",
    "PLURAL",
    "POSSESSIVE",
    "COMPARISON",
    "CONJUNCTION",
    "MODAL",
    "PASSIVE",
    "GERUND",
    "INFINITIVE",
    "PARTICIPLE",
    "CLAUSE",
    "FRAGMENT",
    "RUN_ON",
)

GRAMMAR_CATEGORIES = {
    "GRAMMAR",
    "TYPOS",
    "CONFUSED_WORDS",
    "TYPOGRAPHY",
    "CASING",
}

STYLE_CATEGORIES = {"STYLE", "REDUNDANCY", "PUNCTUATION", "SEMANTICS"}

SPELLING_CATEGORIES = {"MORFOLOGIK", "SPELLING", "MORFOLOGIK_RULE"}

STYLE_RULE_PREFIXES = (
    "REDUNDANCY",
    "WORDINESS",
    "REPETITION",
    "CLARITY",
    "FORMALITY",
)
