"use client";

import { useState, useEffect } from "react";
import Link from "next/link";
import { Logo } from "@/app/components/Logo";
import {
  SectionCard,
  ContentList,
  Text,
  ExternalLink,
  InternalLink,
} from "@/app/components/ContentComponents";

export default function TermsPage() {
  const [lastUpdated, setLastUpdated] = useState<string>("");

  useEffect(() => {
    // Only compute date on client to avoid hydration mismatch
    setLastUpdated(
      new Date().toLocaleDateString("en-US", {
        year: "numeric",
        month: "long",
        day: "numeric",
      }),
    );
  }, []);

  return (
    <>
      <header className="header" lang="en">
        <div className="header-content">
          <div className="logo-group">
            <Logo />
          </div>
          <nav className="header-actions" aria-label="Terms actions">
            <Link href="/" className="nav-back-link">
              <span aria-hidden="true">←</span> Back to Home
            </Link>
          </nav>
        </div>
      </header>

      <div className="container" lang="en">
        <div style={{ maxWidth: "800px", margin: "0 auto" }}>
          <h1 className="page-title">Terms of Service</h1>
          {lastUpdated && <p className="page-subtitle">Last updated: {lastUpdated}</p>}

          <SectionCard title="📋 Agreement to Terms" isFirst>
            <Text>
              By accessing or using Writeo, you agree to be bound by these Terms of Service. If you
              disagree with any part of these terms, you may not access the service.
            </Text>
          </SectionCard>

          <SectionCard title="👶 Age & Parental Guidance">
            <Text>
              <strong>Writeo is designed to be safe for users of all ages.</strong> For detailed
              information about children's privacy, age guidelines, and parental guidance, please
              see the <InternalLink href="/privacy">Privacy Policy</InternalLink>.
            </Text>
          </SectionCard>

          <SectionCard title="👤 Use of Service">
            <Text>
              Writeo is a study tool designed to help you improve your writing skills through
              automated feedback. You agree to:
            </Text>
            <ContentList>
              <li>Use the service only for lawful purposes</li>
              <li>Not attempt to abuse, disrupt, or harm the service</li>
              <li>Not use the service to generate content for academic dishonesty or plagiarism</li>
              <li>Respect the intellectual property rights of others</li>
            </ContentList>
          </SectionCard>

          <SectionCard title="🤖 AI-Generated Feedback">
            <Text>
              Writeo uses AI models to provide automated feedback on your writing. You understand
              that:
            </Text>
            <ContentList>
              <li>
                Feedback is generated by AI and should be used as a learning aid, not as a
                definitive assessment
              </li>
              <li>Scores and feedback are advisory and may not always be accurate</li>
              <li>
                You are responsible for your own learning and should use feedback appropriately
              </li>
              <li>The service is provided "as is" without warranties of any kind</li>
            </ContentList>
          </SectionCard>

          <SectionCard title="⚡ API Usage & Rate Limiting">
            <Text>
              Writeo implements rate limiting to ensure fair usage and service stability. The
              following limits apply:
            </Text>
            <ContentList>
              <li>
                <strong>Essay submissions:</strong> 10 submissions per minute per IP address
              </li>
              <li>
                <strong>General API requests:</strong> 30 requests per minute per IP address
              </li>
              <li>
                <strong>Results retrieval:</strong> 60 requests per minute per IP address
              </li>
            </ContentList>
            <Text>
              If you exceed these limits, you will receive a 429 (Too Many Requests) error. Rate
              limits reset after 60 seconds. These limits are subject to change and may vary for
              different types of usage.
            </Text>
            <Text note>
              <strong>Note:</strong> Rate limits are applied per IP address. For API access with
              higher limits, please contact the project maintainer via{" "}
              <ExternalLink href="https://discord.gg/YxuFAXWuzw">Discord server</ExternalLink>.
            </Text>
          </SectionCard>

          <SectionCard title="📝 Intellectual Property">
            <Text>
              <strong>Your Content:</strong> You retain all rights to the essays and content you
              submit to Writeo. Writeo does not claim ownership of your writing.
            </Text>
            <Text>
              <strong>Writeo Service:</strong> Writeo is a personal project by Robert Gilks. The
              source code is available under the Apache License 2.0 and may be copied, modified, and
              distributed in accordance with that license. The Writeo name and branding are
              protected by copyright.
            </Text>
          </SectionCard>

          <SectionCard title="⚠️ Disclaimer of Warranties">
            <Text>
              Writeo is provided "as is" and "as available" without any warranties, express or
              implied. We do not guarantee that:
            </Text>
            <ContentList>
              <li>The service will be uninterrupted or error-free</li>
              <li>Feedback will be accurate or suitable for your purposes</li>
              <li>The service will meet your specific requirements</li>
            </ContentList>
          </SectionCard>

          <SectionCard title="🔒 Limitation of Liability">
            <Text>
              To the maximum extent permitted by law, Writeo and its operators shall not be liable
              for any indirect, incidental, special, consequential, or punitive damages, or any loss
              of profits or revenues, whether incurred directly or indirectly, or any loss of data,
              use, goodwill, or other intangible losses resulting from your use of the service.
            </Text>
          </SectionCard>

          <SectionCard title="🔄 Changes to Terms">
            <Text>
              We reserve the right to modify these terms at any time. We will update the "Last
              updated" date at the top of this page when changes are made. Your continued use of the
              service after changes constitutes acceptance of the new terms.
            </Text>
          </SectionCard>

          <SectionCard title="📧 Contact">
            <Text>
              If you have questions about these Terms of Service, please contact the project
              maintainer via{" "}
              <ExternalLink href="https://discord.gg/YxuFAXWuzw">Discord server</ExternalLink>. For
              privacy-related inquiries, please see our{" "}
              <InternalLink href="/privacy">Privacy Policy</InternalLink>.
            </Text>
          </SectionCard>

          <div style={{ marginTop: "var(--spacing-xl)", textAlign: "center" }}>
            <Link href="/" className="btn btn-primary">
              ← Back to Home
            </Link>
          </div>
        </div>
      </div>
    </>
  );
}
